Added sync and reconfigured async to the aio module
aerospike/aerospike-proximus-client-python pull request #12
Opened 2024-04-26 23:45 UTC by DomPeliniAerospike

Change file structure for better organization
Added helper functions to share code beetween base and aio modules Modified channel_provider to block on channel.close() Added async and aio test modules
Changed names of VectorDbClient to client

2024-04-27 00:06 UTC, jdogmcsteezy commented on src/aerospike_vector/__init__.py
> +from .client import Client
what about `types`?

2024-04-27 01:24 UTC, jdogmcsteezy requested changes
Looks good over all. Nicely removes code duplication!

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/aio/admin.py
> +            admin_helpers.check_timeout(start_time, timeout)
same

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/aio/client.py
> +    Aerospike Vector Admin Client
mention Async

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/aio/client.py
listener_name in the __init__ should be `is_listener_name: Optional[str] = None,`

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/aio/internal/channel_provider.py
> +        asyncio.create_task(self._tend())
I think you might actually get some Runtime warnings since you at no point await the result. I could be wrong though.

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/client.py
> +        listener_name: str = None,
```suggestion
        listener_name: Optional[str] = None,
```

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/client.py
> +        limit: int,
We should probably have a default for this

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/internal/channel_provider.py
> +        threading.Timer(1, self._tend).start()
I wonder if we need to keep track of this thread. 1 second is not a big deal but in the future if the thread interval is longer could it stop the application from shutting down or am I making that up?

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/shared/admin_helpers.py
> +def get_index_stub(self):
Might be a good idea to make the Async and Sync clients inherit from a Base class then things like get_index_stub could be members of the Base. I only say that because 1, they must mirror each other and 2 you are using the word `self` here instead of passing in the `_channelProvider`.

p.s. it should be `_channel_provider` right?

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/shared/base_channel_provider.py
> +class BaseChannelProvider(object):
O look, it is done here

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/shared/base_channel_provider.py
> +        self._nodeChannels[node] = ChannelAndEndpoints(
```suggestion
        self._node_channels[node] = ChannelAndEndpoints(
```
?

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/shared/channel_provider_helpers.py
> +    if new_cluster_id == self._clusterId:
```suggestion
    if new_cluster_id == self._cluster_ID:
```

2024-04-27 01:24 UTC, jdogmcsteezy commented on src/aerospike_vector/shared/client_helpers.py
> +def prepare_put(self, namespace, key, record_data, set_name, logger) -> None:
Why not apart of a subclass if you are using `self` here?

2024-04-29 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector/__init__.py
> +from .client import Client
This just allows the client to be accessed as
`from aerospike_vector_search import Client`
rather than
`from aerospike_vector_serach import client.Client`

2024-04-29 15:30 UTC, DomPeliniAerospike commented on src/aerospike_vector/types.py
Correcting this in next commit before release.

2024-04-29 15:31 UTC, DomPeliniAerospike commented on src/aerospike_vector/aio/admin.py
> +            admin_helpers.check_timeout(start_time, timeout)
We should handle this when we handle exception handling more broadly, which will need to be done.

2024-04-29 16:08 UTC, DomPeliniAerospike commented on src/aerospike_vector/aio/client.py
Following up with you on this.

2024-04-29 16:16 UTC, DomPeliniAerospike commented on src/aerospike_vector/aio/internal/channel_provider.py
> +        asyncio.create_task(self._tend())
I think since this returns a task rather than a coroutine, you don't need to await.

If it's a coroutine, you get this error:
`
/home/dpelini/Documents/reldawg/clawn/src/aerospike_vector/aio/internal/channel_provider.py:27: RuntimeWarning: coroutine 'ChannelProvider._tend' was never awaited
    self._tend()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
`

When you wrap the coroutine with a task, this error disappears. I think this practice is fine.

2024-04-29 16:17 UTC, DomPeliniAerospike commented on src/aerospike_vector/aio/admin.py
> +            admin_helpers.check_timeout(start_time, timeout)
We should handle this when we handle exception handling more broadly, which will need to be done.

2024-04-29 16:20 UTC, DomPeliniAerospike commented on src/aerospike_vector/internal/channel_provider.py
> +        threading.Timer(1, self._tend).start()
If tend_interval becomes a tune-able variable, then we would need to track it to force the client to close.  Since we haven't done that, we shouldn't take action at this time, but we should monitor this.

2024-04-29 17:35 UTC, DomPeliniAerospike commented on src/aerospike_vector/shared/admin_helpers.py
> +def get_index_stub(self):
Brain fart.  Changing this in the next commit.

2024-04-29 17:35 UTC, DomPeliniAerospike commented on src/aerospike_vector/shared/base_channel_provider.py
> +class BaseChannelProvider(object):
Yes, will follow this model to implement others.

2024-04-29 17:40 UTC, DomPeliniAerospike commented on src/aerospike_vector/shared/base_channel_provider.py
> +        self._nodeChannels[node] = ChannelAndEndpoints(
Changed in next commit.

2024-04-29 17:45 UTC, DomPeliniAerospike commented on src/aerospike_vector/shared/client_helpers.py
> +def prepare_put(self, namespace, key, record_data, set_name, logger) -> None:
Addressed in next commit.

2024-04-29 17:46 UTC, DomPeliniAerospike commented on src/aerospike_vector/client.py
> +        limit: int,
We will need to consult Adam to set these, I will address this in the next release.

2024-04-30 17:04 UTC, merged