aerospike-vector-search release 0.5.1
aerospike/aerospike-proximus-client-python pull request #15
Opened 2024-05-02 22:08 UTC by DomPeliniAerospike

Fixed tending bug that occurred when node_channels were deleted Made helper functions private
Optimized async _tend function by using asyncio.gather Added _tend_checks to ensure tending doesn't cause close call to hang.

2024-05-03 17:40 UTC, jdogmcsteezy requested changes

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +    async def _check_tend(self):
I  think this is better replaced by an event https://docs.python.org/3/library/asyncio-sync.html#asyncio.Event

This will remove the need for a sleep by allowing the eventloop to handle signaling between coroutines

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +    async def _check_tend(self):
I am thinking you can have an Event call `initialized` and in `check_tend()` you would just do `await initialized.wait()`. No need for a loop

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        while not self._tend_ended:
See my comment below about an Event. This likely be replaced the same way

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            self._tend_ended = True
Event

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        for channel in channels:
You might benefit from a helper here. The call to GetClusterEndpoints is dependent on ClusterInfoStub. Right now we need to wait for every ClusterInfoStub call to finish before we can make any GetClusterEndpoints calls. Really though, a GetClusterEndpoints call can be made when the associated ClusterInfo call is made. Hope that makes sense. 

If you add a helper that does both it might clean the code up and keep you from needing to keep track of the stubs.  You could then call `asyncio.gather` on your helper for every channel

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +                        tasks.append(channel_endpoints.channel.close())
One thing to note here, and maybe it does not matter but, channel_endpoints.channel.close() is not scheduled on the eventloop until they are awaited on line 126. Also, calling them `tasks` it technically incorrect since a task in asyncio is different from a coroutine. 

If you want them to run in the background between line 105 and 126 you need to use create_task I believe

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._tend_initalized = True
trigger the event

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/internal/channel_provider.py
> +        while not self._tend_ended:
Also an Event https://docs.python.org/3/library/threading.html#event-objects

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/internal/channel_provider.py
> +            self._tend_ended = True
trigger event here

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/internal/channel_provider.py
> +        for channel in channels:
This should also be parallelized in the future I think

2024-05-03 17:40 UTC, jdogmcsteezy commented on src/aerospike_vector_search/internal/channel_provider.py
> +        for channel in channels:
We also need some unittests for the tend calls since I doubt our integration tests run with more than 1 vector node

2024-05-06 18:34 UTC, DomPeliniAerospike commented on pyproject.toml
> +version = "0.5.1dev3"
Yes. This is used to create a testpypi page. I will correct this when I do my final commit.

2024-05-06 19:05 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +        await self._channel_provider._check_tend()
I'll change to is_ready in final commit.

2024-05-06 19:05 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +                        tasks.append(channel_endpoints.channel.close())
You are right. Task just looks better to me, but it is confusing so I'll change it.

2024-05-06 19:24 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +    async def _check_tend(self):
Yes. This is better than a lock or a boolean.  I will change this in the final commit.

2024-05-06 19:27 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        for channel in channels:
I will make a ticket for this, but since it works for now, I will clean up in a future release.

2024-05-06 19:36 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +        for channel in channels:
Added parallelism to tending will be a new ticket, but I should delay the release further.  I will create the ticket.

As far as the tending unittests, this would be a good feature, as we will only test one node. However, I feel like mocking all the stub calls would be an undertaking. I will make a ticket for this, but I'm not sure about the priority.

2024-05-06 19:38 UTC, DomPeliniAerospike commented
Merging into dev, creating a new PR to get the changes reviewed.

2024-05-06 19:38 UTC, merged