Added changes for 0.6.0
aerospike/aerospike-proximus-client-python pull request #19
Opened 2024-05-13 20:11 UTC by DomPeliniAerospike

Updated proto files.
Added insert, update, upsert and removed put.
Added delete.
Changed any usage of "bin" to "field".
Fixed tending bug related to deleting endpoints.
Updated tests to mathc new APIs.
Removed any usage of "digest".

2024-05-13 21:58 UTC, jdogmcsteezy requested changes

2024-05-13 21:58 UTC, jdogmcsteezy commented on pyproject.toml
> +version = "0.6.0.dev2"
I know you know

2024-05-13 21:58 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/client.py
> +        except grpc.RpcError as e:
I think it would be easy to wrap these with a generic error like `AVSError` or `AVSServerError` -> `AVSError`

2024-05-13 21:58 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/client.py
> +        except grpc.RpcError as e:
I think I may need this before I can PR into Langchain

2024-05-13 21:58 UTC, jdogmcsteezy commented on src/aerospike_vector_search/client.py
Should is_indexes need both namespace and index_namespace?

2024-05-13 21:58 UTC, jdogmcsteezy commented on src/aerospike_vector_search/shared/client_helpers.py
> +                type=transact_pb2.ProjectionType.SPECIFIED, fields=field_names
```suggestion
                type=transact_pb2.ProjectionType.SPECIFIED, fields=exclude_field_names
```

2024-05-13 21:58 UTC, jdogmcsteezy commented on src/aerospike_vector_search/shared/client_helpers.py
> +                type=transact_pb2.ProjectionType.SPECIFIED, fields=field_names
Is this the place we should check that they are mutually exclusive?

2024-05-13 22:05 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
I haven't gotten word from Ashish and forgot to ask at the standup.  I'll ask Ashish and punt this to another release.

2024-05-13 22:18 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +        except grpc.RpcError as e:
Adding exception to next commit.

2024-05-13 22:19 UTC, DomPeliniAerospike commented on pyproject.toml
> +version = "0.6.0.dev2"
Fixing in next commit.

2024-05-14 00:16 UTC, DomPeliniAerospike commented
Committing here and opening new commit for changes.

2024-05-14 00:16 UTC, merged